---
rules:
  - hdtv:
      screen_size: 720p+
      type: tv
      extraction_location: "/home/scripter/tmp/TvShows"
  - hdtv2:
      screen_size: 480p+
      type: tv
      extraction_location: "/mnt/media/TvShows"
  - movies:
      screen_size: 720p
      type: movie
      extraction_location: "/mnt/media/Movies"
settings:
  - guessit:
      ip: 192.168.88.166
      port: 5000
  - regex: "^((?!sample)(?!part).)*\.(mkv|mp4)"